# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FirebaseAuth' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FirebaseAuth
  pod 'Firebase/Auth'

  target 'FirebaseAuthTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FirebaseAuthUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
